# Generated by Django 4.0.4 on 2022-05-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('date', 'start_time', 'end_time'), 'verbose_name_plural': 'Offerings'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('date', 'start_time', 'end_time'), 'verbose_name_plural': 'Requests'},
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='offer',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
