# Generated by Django 4.0.4 on 2022-05-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_commerce', '0003_offer_accepted_request_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
