# Generated by Django 4.0.4 on 2022-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_commerce', '0004_alter_offer_start_time_alter_request_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
